### PR TITLE
Add the option to run tests once.

### PR DESCRIPTION
**Pull request by mahinshaw**

### CODE REVIEW

**Comment by jakemcc** [comment]
Thanks for the PR. I haven't had a chance to check it out and try it yet but gave it a quick glance and looks good.

Seems like a slightly weird feature to have in a test runner designed to run tests over and over again. Mind sharing whats the motivation? My guess is that its the quiet test runner but would like to confirm.

**Comment by mahinshaw** [comment]
Yeah, it's definitely a strange feature. We have an in house test framework with a custom emitter, and it would be nice to have this to run on our ci server so we get nice outputs, unlike what we currently get with lein test.

**Comment by jakemcc** [comment]
Ahh, I forgot about that feature. Thanks for responding. Taking it for a spin now.

**Comment by jakemcc** [comment]
Thanks for the contribution. I'm going to merge.

**Comment by mahinshaw** [comment]
Appreciated!

**Comment by jakemcc** [comment]
Released version `[com.jakemccrary/lein-test-refresh "0.13.0"]` with this feature.

I changed the flag to be `:run-once` instead of `:once`.

Thanks. Really glad to see the project being used, especially for uses I didn't originally think of.

**Comment by mahinshaw** [comment]
Thanks for the heads up. Already putting it to use!

**Pull request merged**
