### PR TITLE
Add debug mode

### PR DESCRIPTION
**Pull request by paintparty**
Hi!

Thanks for making `test-refresh`, great library!

I use `test-refresh`, as intended, to automatically run tests in projects that I'm working on.

Over time, I found that more often I would use `test-refresh` as a hot-reloading system when working in JVM Clojure. This means I would temporarily disable all tests and just call a single public function in my project so that I can observe the execution at different points using tapping/debugging macros from [Fireworks](https://github.com/paintparty/fireworks) that print and return forms. You can get a sense of what this looks like by checking out the screen recording below. It shows `test-refresh` running in an integrated editor terminal, with the the editor's auto-save-with-delay automatically triggering the reloads. Just to be clear, this kind of hot-reloading workflow does not depend on Fireworks - it is achievable with similar libs such as [playback](https://github.com/gnl/playback), [debux](https://github.com/philoskim/debux), [hashp](https://github.com/weavejester/hashp), [telemere](https://github.com/taoensso/telemere), [ken](https://github.com/amperity/ken), [spyscope](https://github.com/dgrnbrg/spyscope), [omni-trace](https://github.com/cyrik/omni-trace), [postmortem](https://github.com/athos/postmortem), [sayid](https://github.com/clojure-emacs/sayid), or the user's own hand-rolled debugging or tapping functions/macros:

fw-tour-intro-light

My global profile definded in `~/.lein/profiles.clj`:

```Clojure
 {:user {:dependencies [[pjstadig/humane-test-output "0.11.0"]]
        :injections [(require 'pjstadig.humane-test-output)
                     (pjstadig.humane-test-output/activate!)]
        :plugins [[com.jakemccrary/lein-test-refresh "0.5.5"]]
        :test-refresh {:quiet             true
                       :changes-only      true
                       :notify-on-success false

                       ;; New options:
                       
                       ;; Uncomment next 2 lines for debug mode
                       ;; Comment them out if you want to run tests
                       :debug             true
                       :banner            "🔥"

                       ;; Uncomment next line for custom banner in testing mode
                       ;; :banner             "📋 Running tests..."

                       ;; This clears the console between reloads, preserving scrollback
                       :clear             true
                       }}}
```
<br>

### The 3 options that I added to enable this workflow:

`:debug` - Disables all tests and reporting. Surfaces errors. Defaults to `false`

`:banner` - Allows user to supply their own banner. This can be used both in `:debug` mode as well as the normal default test running mode. You can supply an empty string to disable banner printing. If not supplied, current `test-refresh` banner with stars is used.

`:clear` - Clears the terminal in between reloads, preserving scrollback. When `:debug` is set to true, this is enabled by default. Defaults to `false`, so user must opt-in to this feature when running tests.

<br>

### Testing:

I've tested the `:clear` feature on MacOS 12.6 with the following terminal emulators:

| Emulator       | Clears?    | Preserves Scrollback? 
| :---                | :---           | :---
|  iTerm             | ✅            | ✅                 
|  Alacritty         | ✅           | ✅                 
|  Terminal        | ✅            | ✅                 
|  Warp             | ✅            | ✅                
|  Kitty              | ✅            | ×                 
|  WezTerm      | ✅            | ×                 

And the following editor-integrated terminal emulators:

| Editor                                    | Clears?       | Preserves Scrollback? 
| :---                                        | :---             | :---
| Intellij IDEA                           | ✅               | ✅                 
| VSCode                                | ✅                | ✅                 
| SublimeText (w Terminus)  | ✅                | ✅
| Neovim (VT220/xterm)       | ✅                | ×
| Emacs (ansi-term)              | ✅                | × 
| Emacs (eshell)                     | ×                 | × 

I haven't tested the `:clear` feature on linux but would expected similar results as above.

I wouldn't expect the `:clear` feature to work on windows, but I think that could be easily added in the future.

### CODE REVIEW

**Comment by jakemcc** [comment]
Thanks for the nice write-up and all the testing. Just posting a comment to
acknowledge I've seen this, though haven't had time yet to look at it
closely. I'll attempt to do so within the next week, though it may need to
wait till this upcoming weekend.

**Comment by paintparty** [comment]
Thanks for the prompt reply. No rush at all. Look forward to hearing your thoughts after you get a chance to check it out.

**Comment by jakemcc** [comment]
Sorry for the delay, this holiday season has sucked up more of my open-source time than I thought it would.

I've taken a quick look and I think it is looking good, though I'm still planning on taking a deeper look and actually run it before merging. I'm hopeful that will happen either this week or next.

Thanks for the contribution. Looking forward to getting it in.

**Comment by paintparty** [comment]
Thanks for the update @jakemcc!

**Comment by jakemcc** [comment]
Seems mostly good to me, though it removes the default banner from the deps.edn code path since the resolving happens in a leiningen specific code path. This could be fixed by moving that code that does the defaulting over to the shared code.

I'll merge and fix that. Thank you for the contribution

**Comment by jakemcc** [comment]
Released as `0.26.0` 🎉

**Pull request merged**
